; ZONA DE DATOS *************************************
__CONFIG _CP_OFF & _WDT_OFF &_PWRTE_ON & _XT_OSC
LIST P=PIC16F84A
INCLUDE <P16F84A.INC>

;ZONA DE VARIABLES*********************************************************************************************
CBLOCK	0X0C		; SE INICIALIZA LA MEMORIA
	NUMERO			; VARIABLE QUE LLEVARA EL CONTADOR DE 0-9 Y DE A-F
	CONTADOR		; LLEVA EL TIEMPO EN CICLOS DE RELOJ
ENDC
	ORG			0
	GOTO		START	; CICLO
	ORG			5
; CONFIGURACION************************************************************************************************
START		BSF 	STATUS,5		; BANCO 1 ACTIVA EL BIT B DE F
			CLRF	TRISB			; PORTB ES LA SALIDA
			MOVLW	0X1F			; MOVER A LA PARTE BAJA DEL REGISTRO DE MEMORIA RA0 RA4 SON LAS ENTRADAS
			MOVWF	TRISA			; MOVER A F A TRISA
			MOVLW	B'11000111'		; ASIGNA 256 AL TIMER
			MOVWF	OPTION_REG
			BCF		STATUS,5		; CARGAR EL CONTENIDO DE LA POSICION 5 AL BANCO 0
			CLRW					; DEJA A W=0
			CLRF	NUMERO			; LIMPIA LA VARABLE NUMERO
; INICIO*******************************************************************************************************
MAIN		MOVF	NUMERO,W		; TOMA EL CONTENIDO DE W Y LO CARGA EN F
			CALL	TABLA			; LLAMA A LA FUNCION TABLA
			MOVWF	PORTB			; MUESTRA EL VALOR QUE TOMO LA TABLA
			CALL	PAUSE_1000		; LLAMA A LA FUNCION PAUSE
			INCF	NUMERO,F		;  REALIZA UN INCREMENTO DE LA VARIABLE 1
			MOVF	NUMERO,W		; SE CARGA LA VARIABLE EN W
			XORLW	0X10			; SE COMPARA SI ES QUE LLEGA AL REGISTRO 10
			BTFSS	STATUS,Z		; VERIFA SI HA LLEGADO
			GOTO	MAIN			; SE REGRESA A MAIN
			CLRW					; AL LLEGAR A 10 SE RESETEA A F
			CLRF	NUMERO			; SE LIMPIA A NUMERO
			GOTO	MAIN			; SE REGRESA A MAIN


; FIN DE INICIO************************************************************************************************
; PAUSE_1000 SE REALIZA UN RETARDO DE UN SEGUNDO***************************************************************
PAUSE_1000	MOVLW	0X02			; SE LE ASIGNA 1000 AL CONTADOR
			MOVWF	CONTADOR		; SE MUEVE EL VALOR DEL CONTADOR DE A a F
DELAY		BCF		INTCON,T0IF		; SE LIBERA EL BIT DE DESBORDAMIENTO TMR0
			MOVLW	09				; SE LE CARGA EL 217 A W
			MOVWF	TMR0			; A TMR0
DELAY2		BTFSS	INTCON,T0IF		; SE LIBERA EL BIT DE DESBORDAMIENTO DEL TMR0
			GOTO	DELAY2			; BUCLE DEL DELAY2
			DECFSZ	CONTADOR,F		; DECREMENTA EN 1 EL CONTADOR
			GOTO	DELAY			; BUVLEN EN DELAY
			RETURN					; REGRESA

; TABLA********************************************************************************************************
TABLA		ADDWF	PCL,F			; SE INCIALIZA LA FUNCION TABLA CON EL CONTENIDO DE F
			RETLW	B'00111111'		; 0 EN CATADO DE 7 SEGMENTOS
			RETLW	B'00000110'		;1
			RETLW	B'01011011'		;2
			RETLW	B'01001111'		;3
			RETLW	B'01100110'		;4
			RETLW	B'01101101'		;5
			RETLW	B'01111101'		;6
			RETLW	B'01000111'		;7
			RETLW	B'01111111'		;8
			RETLW	B'01100111'		;9
			RETLW	B'01110111'		;A
			RETLW	B'01111100'		;b
			RETLW	B'00111001'		;C
			RETLW	B'01011110'		;d
			RETLW	B'01111001'		;E
			RETLW	B'01110001'		;F
END		
